### ISSUE TITLE
7. As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-23-smart-shopping-list#8]
AC:

* The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

**Comment by yenly** [comment]
As discussed in our weekly sync, this issue would also handle saving the user token to Firestore. 
Example use case:

1. I create a new list. I haven't added any items yet.
2. I give that token to my friend to join and add items.
3. When my friend comes to the app and entered the token, it should display a list view with no items.

**Comment by zeeatwork** [comment]
> As discussed in our weekly sync, this issue would also handle saving the user token to Firestore.
> Example use case:
> 
> 1. I create a new list. I haven't added any items yet.
> 2. I give that token to my friend to join and add items.
> 3. When my friend comes to the app and entered the token, it should display a list view with no items.

Jessica and I worked on our our PR today and realized that the use case stated above makes it impossible to pass our Acceptance Criteria for the week.  

- In Firestore, every collection (for us, this would be the user token) is required to have a document (for us, documents are shopping list items).
- As a workaround, we generated a sharable token but added a 'dummy item',  without the dummy item (or an initial item from the original user), the token will not exist outside of local storage.
- Another possible workaround is to make the collection data structure deeper, so that our user token is stored as a document and we create a sub-collection  becomes the shopping list. The sub-collection can be empty
- The secondary solution meets both sets of criteria, but would require us to refactor all code that queries firestore currently 

Jessica and I have discussed all options with Skyler via Zoom this evening.  We think it makes sense to honor the original AC.  Our current PR creates a sharable token in Firebase with a dummy item, but can quickly be refactored to conditionally keep our first item prompt without the dummy item.

**Comment by yenly** [comment]
From my understanding of testing the PRs from last week, the timing of when the token is saved to the database will cause an error for the use case I suggested.

When a user creates a new token:

1. it saves to state and local storage, not to Firestore
2. **token is only saved to Firestore when they add their first item**

But if they don't add an item and share their token with a friend, that friend will always get an error when trying to access the empty list.

For the original AC, your `listItems` is defined in App.js as an empty array as its default value (line 13).  If you pass that down to List.js, then you can do the conditional to render your prompt when the list is empty. **Currently, you have `listItems` defined twice in App. js and in List.js.** 

@laurenyz  had recommended passing listItems down to List.js in last week's PR but I think it got lost in the conversation due to merges/refactoring. 
<img width="733" alt="Screen Shot 2021-04-27 at 8 25 20 AM" src="https://user-images.githubusercontent.com/6759658/116268415-25d74380-a732-11eb-8b9c-9de8acd89120.png">

**Comment by jssckbl** [comment]
I do recall now when laurenyz made that suggestion, and I apologize it got lost in the mix! I clicked resolve and should not have.

The general idea of timing being important as to whether something works or not makes sense. 

The two things I am stuck on at the moment are:

1. I am trying to understand is where `listItems` is at in `List.js`. There is a `listItem` though. 

2. The research that Zenzi and I did regarding Firestore kept saying that it is not possible to start a collection without a document in it. Which in general, doesn't make sense, but that's how I am interpreting the following:

[Understand Cloud Firestore](https://firebase.google.com/docs/firestore/data-model)

<img width="943" alt="cloudFirestore" src="https://user-images.githubusercontent.com/38255956/116478674-0cbeb780-a844-11eb-8ea7-913bfed1d2c2.png">


I believe the most recent conclusion Zenzi and I came to is that we are either misinterpreting what this is saying, or we need to restructure the database by including sub-documents, since it seems that a collection can exist with nothing in the documents, but something in the sub-documents.

**Comment by yenly** [comment]
There is an option of creating a new collection called `tokenList` to keep a list of all tokens to check against. This wouldn't require refactoring and restructuring the current shopping list data. The benefit of NoSQL is the ability to create all kinds of collections with different data structures. 

<img width="954" alt="Screen Shot 2021-04-28 at 3 55 32 PM" src="https://user-images.githubusercontent.com/6759658/116482549-3a066800-a83a-11eb-9043-50f7da4cf544.png">
